/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unal.finanzas.proforma.vista;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;

/**
 *
 * @author ricardo
 */
public class DecisionesProforma extends javax.swing.JPanel {

    /**
     * Creates new form DecisionesProforma
     */
    public DecisionesProforma() {
        initComponents();
        unitsDemanded.requestFocusInWindow();
    }
    
    public JFormattedTextField getUnitsDemanded() {
        return unitsDemanded;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unitsDemandedLabel = new javax.swing.JLabel();
        unitsDemanded = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Decisiones Pro forma Periodo --", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        setLayout(new java.awt.GridLayout(8, 2));

        unitsDemandedLabel.setText("Units Demanded:");
        add(unitsDemandedLabel);

        unitsDemanded.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        unitsDemanded.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                unitsDemandedPropertyChange(evt);
            }
        });
        add(unitsDemanded);

        jLabel2.setText("Short term investments:");
        add(jLabel2);

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        jFormattedTextField2.setValue(0.0);
        add(jFormattedTextField2);

        jLabel3.setText("Short term loan:");
        add(jLabel3);

        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        jFormattedTextField3.setValue(0.0);
        add(jFormattedTextField3);

        jLabel4.setText("Three-year loan:");
        add(jLabel4);

        jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        jFormattedTextField4.setValue(0.0);
        add(jFormattedTextField4);

        jLabel5.setText("Prefered stock yield:");
        add(jLabel5);

        jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        jFormattedTextField5.setValue(0.0);
        add(jFormattedTextField5);

        jLabel6.setText("Capital gains rate:");
        add(jLabel6);

        jFormattedTextField6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        jFormattedTextField6.setValue(0.0);
        add(jFormattedTextField6);

        jLabel7.setText("Two year loan:");
        add(jLabel7);

        jFormattedTextField7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        jFormattedTextField7.setValue(0.0);
        add(jFormattedTextField7);

        jLabel8.setText("Long-term loan:");
        add(jLabel8);

        jFormattedTextField8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));
        jFormattedTextField8.setValue(0.0);
        add(jFormattedTextField8);
    }// </editor-fold>//GEN-END:initComponents

    private void unitsDemandedPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_unitsDemandedPropertyChange
        if (unitsDemanded.getValue() == null) {
            unitsDemandedLabel.setIcon(new ImageIcon(getClass().getResource("/co/edu/unal/finanzas/proforma/resources/x.png")));
            
        } else {
            unitsDemandedLabel.setIcon(null);
        }
    }//GEN-LAST:event_unitsDemandedPropertyChange
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JFormattedTextField unitsDemanded;
    private javax.swing.JLabel unitsDemandedLabel;
    // End of variables declaration//GEN-END:variables
}
