/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unal.finanzas.proforma.vista;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author ricardo
 */
public class DecisionesFinancieras extends javax.swing.JPanel {

    private NumberFormat amountDisplayFormat;
    private NumberFormat amountEditFormat;

    /**
     * Creates new form DecisionesFinancieras
     */
    public DecisionesFinancieras() {
        setUpFormats();
        initComponents();
    }

    private void setUpFormats() {
        // NumberFormat nf=NumberFormat.getInstance(Locale.US);
        amountDisplayFormat = NumberFormat.getCurrencyInstance(Locale.US);
        amountDisplayFormat.setMinimumFractionDigits(2);
        amountEditFormat = NumberFormat.getNumberInstance(Locale.US);


    }

    private void camposObligatorios(JFormattedTextField campo, JLabel etiqueta) {
        if (campo.getValue() == null) {
            etiqueta.setIcon(new ImageIcon(getClass().getResource("/co/edu/unal/finanzas/proforma/resources/x.png")));

        } else {
            etiqueta.setIcon(null);
        }
    }

    public JFormattedTextField getShortTermLoan() {
        return shortTermLoan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        shortTermLoan = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        preferedSharesLabel = new javax.swing.JLabel();
        preferedShares = new javax.swing.JFormattedTextField();
        commonSharesLabel = new javax.swing.JLabel();
        commonShares = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Decisiones Financieras"));
        setLayout(new java.awt.GridLayout(2, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DEBT:"));
        jPanel1.setLayout(new java.awt.GridLayout(4, 2));

        jLabel1.setText("Short-term loans:");
        jPanel1.add(jLabel1);

        shortTermLoan.setFormatterFactory(new DefaultFormatterFactory(
            new NumberFormatter(amountDisplayFormat),
            new NumberFormatter(amountDisplayFormat),
            new NumberFormatter(amountEditFormat)));
    shortTermLoan.setValue(0);
    jPanel1.add(shortTermLoan);

    jLabel2.setText("Two-year loans:");
    jPanel1.add(jLabel2);

    jFormattedTextField2.setFormatterFactory(new DefaultFormatterFactory(
        new NumberFormatter(amountDisplayFormat),
        new NumberFormatter(amountDisplayFormat),
        new NumberFormatter(amountEditFormat)));
jFormattedTextField2.setValue(0);
jPanel1.add(jFormattedTextField2);

jLabel3.setText("Three-year loans:");
jPanel1.add(jLabel3);

jFormattedTextField3.setFormatterFactory(new DefaultFormatterFactory(
    new NumberFormatter(amountDisplayFormat),
    new NumberFormatter(amountDisplayFormat),
    new NumberFormatter(amountEditFormat)));
    jFormattedTextField3.setValue(0);
    jPanel1.add(jFormattedTextField3);

    jLabel4.setText("Ten-year bonds");
    jPanel1.add(jLabel4);

    jFormattedTextField4.setFormatterFactory(new DefaultFormatterFactory(
        new NumberFormatter(amountDisplayFormat),
        new NumberFormatter(amountDisplayFormat),
        new NumberFormatter(amountEditFormat)));
jFormattedTextField4.setValue(0);
jPanel1.add(jFormattedTextField4);

add(jPanel1);

jPanel2.setBackground(new java.awt.Color(255, 255, 255));
jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "EQUITY"));
jPanel2.setLayout(new java.awt.GridLayout(3, 2));

preferedSharesLabel.setText("Preferred shares:");
jPanel2.add(preferedSharesLabel);

preferedShares.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
preferedShares.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
    public void propertyChange(java.beans.PropertyChangeEvent evt) {
        preferedSharesPropertyChange(evt);
    }
    });
    jPanel2.add(preferedShares);

    commonSharesLabel.setText("Common shares:");
    jPanel2.add(commonSharesLabel);

    commonShares.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
    commonShares.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
        public void propertyChange(java.beans.PropertyChangeEvent evt) {
            commonSharesPropertyChange(evt);
        }
    });
    jPanel2.add(commonShares);

    jLabel7.setText("Common tender price:");
    jPanel2.add(jLabel7);

    jFormattedTextField6.setFormatterFactory(new DefaultFormatterFactory(
        new NumberFormatter(amountDisplayFormat),
        new NumberFormatter(amountDisplayFormat),
        new NumberFormatter(amountEditFormat)));
jFormattedTextField6.setValue(0);
jPanel2.add(jFormattedTextField6);

add(jPanel2);
}// </editor-fold>//GEN-END:initComponents

    private void preferedSharesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_preferedSharesPropertyChange
        camposObligatorios(preferedShares, preferedSharesLabel);    }//GEN-LAST:event_preferedSharesPropertyChange

    private void commonSharesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_commonSharesPropertyChange
        camposObligatorios(commonShares, commonSharesLabel);    }//GEN-LAST:event_commonSharesPropertyChange
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField commonShares;
    private javax.swing.JLabel commonSharesLabel;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField preferedShares;
    private javax.swing.JLabel preferedSharesLabel;
    private javax.swing.JFormattedTextField shortTermLoan;
    // End of variables declaration//GEN-END:variables
}
