/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unal.finanzas.proforma.vista;

import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author ricardo
 */
public class DecisionesCompania extends javax.swing.JPanel {

    private NumberFormat amountDisplayFormat;
    private NumberFormat amountEditFormat;

    /**
     * Creates new form DecisionesCompania
     */
    public DecisionesCompania() {
        setUpFormats();
        initComponents();
    }

    private void setUpFormats() {
        // NumberFormat nf=NumberFormat.getInstance(Locale.US);
        amountDisplayFormat = NumberFormat.getCurrencyInstance(Locale.US);
        amountDisplayFormat.setMinimumFractionDigits(2);
        amountEditFormat = NumberFormat.getNumberInstance(Locale.US);


    }

    public JFormattedTextField getUnitsProduce() {
        return unitsProduce;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unitsProduceLabel = new javax.swing.JLabel();
        unitsProduce = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Decisiones Compañia"));
        setLayout(new java.awt.GridLayout(6, 2));

        unitsProduceLabel.setText("Number of units to produce:");
        add(unitsProduceLabel);

        unitsProduce.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        unitsProduce.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                unitsProducePropertyChange(evt);
            }
        });
        add(unitsProduce);

        jLabel2.setText("Per unit price:");
        add(jLabel2);

        jFormattedTextField2.setFormatterFactory( new DefaultFormatterFactory(
            new NumberFormatter(amountDisplayFormat),
            new NumberFormatter(amountDisplayFormat),
            new NumberFormatter(amountEditFormat)));
    jFormattedTextField2.setValue(0);
    add(jFormattedTextField2);

    jLabel3.setText("Dividends per share of common stock:");
    add(jLabel3);

    jFormattedTextField3.setFormatterFactory( new DefaultFormatterFactory(
        new NumberFormatter(amountDisplayFormat),
        new NumberFormatter(amountDisplayFormat),
        new NumberFormatter(amountEditFormat)));
jFormattedTextField3.setValue(0);
add(jFormattedTextField3);

jLabel4.setText("Advertising costs per period:");
add(jLabel4);

jFormattedTextField4.setFormatterFactory( new DefaultFormatterFactory(
    new NumberFormatter(amountDisplayFormat),
    new NumberFormatter(amountDisplayFormat),
    new NumberFormatter(amountEditFormat)));
    jFormattedTextField4.setValue(0);
    add(jFormattedTextField4);

    jLabel5.setText("Demand/price forecast:");
    add(jLabel5);

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Free" }));
    add(jComboBox1);

    jLabel6.setText("Sales discount:");
    add(jLabel6);

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));
    add(jComboBox2);
    }// </editor-fold>//GEN-END:initComponents

    private void unitsProducePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_unitsProducePropertyChange
        if (unitsProduce.getValue() == null) {
            unitsProduceLabel.setIcon(new ImageIcon(getClass().getResource("/co/edu/unal/finanzas/proforma/resources/x.png")));

        } else {
            unitsProduceLabel.setIcon(null);
        }    }//GEN-LAST:event_unitsProducePropertyChange
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JFormattedTextField unitsProduce;
    private javax.swing.JLabel unitsProduceLabel;
    // End of variables declaration//GEN-END:variables
}
