/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unal.finanzas.proforma.vista;

/**
 *
 * @author ricardo
 */
public class SimulacionNuevaVista extends javax.swing.JPanel {

    /**
     * Creates new form SimulacionNuevaVista
     */
    public SimulacionNuevaVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        contenedorForms = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 800));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 700));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridLayout(6, 1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unal/finanzas/proforma/resources/Decisions-Good-decision-icon.png"))); // NOI18N
        jButton1.setText("Decisiones Proforma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unal/finanzas/proforma/resources/Decisions-Good-decision-icon.png"))); // NOI18N
        jButton2.setText("Decisiones Periodo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unal/finanzas/proforma/resources/Play-icon.png"))); // NOI18N
        jButton3.setText("Simular Proforma");
        jButton3.setToolTipText("En proceso...");
        jButton3.setEnabled(false);
        jPanel3.add(jButton3);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unal/finanzas/proforma/resources/SEO-icon.png"))); // NOI18N
        jButton5.setText("Resultados Proforma");
        jPanel3.add(jButton5);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unal/finanzas/proforma/resources/Play-icon.png"))); // NOI18N
        jButton4.setText("Simular Periodo");
        jButton4.setToolTipText("En proceso...");
        jButton4.setEnabled(false);
        jPanel3.add(jButton4);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unal/finanzas/proforma/resources/Line-Graph-icon.png"))); // NOI18N
        jButton6.setText("Resultados Actuales");
        jPanel3.add(jButton6);

        jPanel1.add(jPanel3, java.awt.BorderLayout.EAST);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jLabel2.setText("Periodo:");
        jPanel2.add(jLabel2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5" }));
        jPanel2.add(jComboBox1);

        jPanel4.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        contenedorForms.setBackground(new java.awt.Color(255, 255, 255));
        contenedorForms.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        contenedorForms.setPreferredSize(new java.awt.Dimension(450, 280));
        contenedorForms.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unal/finanzas/proforma/resources/Money-Calculator-icon.png"))); // NOI18N
        contenedorForms.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel4.add(contenedorForms, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        contenedorForms.setVisible(false);
        contenedorForms.removeAll();
        DecisionesProforma formulario = new DecisionesProforma();
        contenedorForms.add(formulario);
        contenedorForms.setVisible(true);
        formulario.getUnitsDemanded().requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        contenedorForms.setVisible(false);
        contenedorForms.removeAll();
        DecisionesActuales formulario = new DecisionesActuales();
        contenedorForms.add(formulario);
        contenedorForms.setVisible(true);
        formulario.defaultPanel();
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorForms;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
